import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPython,
  SiPostgresql,
  SiMongodb,
  SiTensorflow,
  SiPytorch,
  SiTableau,
  SiSnowflake,
  SiAmazonwebservices,
  SiDatabricks,
  SiApachespark,
  SiApacheairflow,
  SiDbt,
  SiPandas,
  SiNumpy,
  SiScipy,
  SiMysql,
  SiKeras,
  SiScikitlearn,
  SiJupyter,
  SiPlotly,
  SiGit,
  SiApachekafka,
  SiDocker,
  SiApachehadoop,
  SiAmazonredshift,
  SiAmazons3,
  SiR,
  SiKubernetes,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  python: SiPython,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  tableau: SiTableau,
  snowflake: SiSnowflake,
  aws: SiAmazonwebservices,
  databricks: SiDatabricks,
  spark: SiApachespark,
  airflow: SiApacheairflow,
  dbt: SiDbt,
  pandas: SiPandas,
  numpy: SiNumpy,
  scipy: SiScipy,
  mysql: SiMysql,
  keras: SiKeras,
  sklearn: SiScikitlearn,
  jupyter: SiJupyter,
  plotly: SiPlotly,
  git: SiGit,
  kafka: SiApachekafka,
  docker: SiDocker,
  hadoop: SiApachehadoop,
  redshift: SiAmazonredshift,
  s3: SiAmazons3,
  r: SiR,
  kubernetes: SiKubernetes,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
